languageCode = "en-us"
title = "Snuff in Sixty"
baseurl = "http://www.snuff.wtf/"
publishDir = "public"
theme = "snuff"

[permalinks]
post = "/:year/:month/:title/"

[params]
subtitle = "60 horror movies in 60 days"
analytics = "UA-102338574-1"